/* Explicit, exercise-specific media mapping.
 *
 * `free` entries use the public-domain Free Exercise DB photo pairs.
 * `repdb` entries use RepDB's attributed free-tier illustrations.
 * A null value is intentional: RSG Coach must never guess a visual from a
 * broad movement category when an exact variant has not been verified.
 */
globalThis.RSG_EXERCISE_MEDIA = Object.freeze({
  'Bänkpress': ['free', 'Barbell_Bench_Press_-_Medium_Grip'],
  'Lutande bänkpress': ['free', 'Barbell_Incline_Bench_Press_-_Medium_Grip'],
  'Lutande Smithpress': ['free', 'Smith_Machine_Incline_Bench_Press'],
  'Hantelpress plan bänk': ['free', 'Dumbbell_Bench_Press'],
  'Lutande hantelpress': ['free', 'Incline_Dumbbell_Press'],
  'Hantelpress golv': ['free', 'Dumbbell_Floor_Press'],
  'Bröstpressmaskin': ['free', 'Machine_Bench_Press'],
  'Bröstpress Hammer Strength': ['free', 'Leverage_Chest_Press'],
  'Pec deck': ['free', 'Butterfly'],
  'Kabelflyes': ['free', 'Cable_Crossover'],
  'Kabelflyes hög-till-låg': ['free', 'Cable_Crossover'],
  'Kabelflyes låg-till-hög': ['free', 'Low_Cable_Crossover'],
  'Hantelflyes': ['free', 'Dumbbell_Flyes'],
  'Lutande hantelflyes': ['free', 'Incline_Dumbbell_Flyes'],
  'Dips': ['free', 'Dips_-_Chest_Version'],
  'Armhävningar': ['free', 'Pushups'],
  'Pullover hantel': ['free', 'Bent-Arm_Dumbbell_Pullover'],

  'Chins': ['free', 'Chin-Up'],
  'Viktade chins': ['free', 'Weighted_Pull_Ups'],
  'Assisterade chins': ['repdb', 'assisted-pull-ups'],
  'Chins assisterade': ['repdb', 'assisted-pull-ups'],
  'Latsdrag': ['free', 'Wide-Grip_Lat_Pulldown'],
  'Latsdrag brett': ['free', 'Wide-Grip_Lat_Pulldown'],
  'Latsdrag neutralt': ['free', 'V-Bar_Pulldown'],
  'Enarms latsdrag': ['free', 'One_Arm_Lat_Pulldown'],
  'Skivstångsrodd': ['free', 'Bent_Over_Barbell_Row'],
  'Pendlayrodd': null,
  'T-bar rodd': ['free', 'Lying_T-Bar_Row'],
  'Bröststödd rodd': ['free', 'Leverage_Iso_Row'],
  'Bröststödd hantelrodd': ['free', 'Dumbbell_Incline_Row'],
  'Hantelrodd bröststöd': ['free', 'Dumbbell_Incline_Row'],
  'Enarmsrodd hantel': ['free', 'One-Arm_Dumbbell_Row'],
  'Enarmsrodd kabel': ['free', 'Seated_One-arm_Cable_Pulley_Rows'],
  'Kabelrodd': ['free', 'Seated_Cable_Rows'],
  'Kabelrodd smalt': ['free', 'Seated_Cable_Rows'],
  'Maskinrodd': ['free', 'Leverage_Iso_Row'],
  'Pullover kabel': ['free', 'Straight-Arm_Pulldown'],
  'Rakarmsdrag': ['free', 'Straight-Arm_Pulldown'],
  'Renegade row': null,
  'Marklyft': ['free', 'Barbell_Deadlift'],
  'Trap bar-marklyft': ['free', 'Trap_Bar_Deadlift'],
  'Ryggresningar': ['free', 'Hyperextensions_Back_Extensions'],

  'Skivstångsshrugs': ['free', 'Barbell_Shrug'],
  'Hantelshrugs': ['free', 'Dumbbell_Shrug'],
  'Smithshrugs': null,
  'Farmers carry': null,

  'Militärpress': ['free', 'Standing_Military_Press'],
  'Sittande hantelpress': ['free', 'Seated_Dumbbell_Press'],
  'Hantelpress': ['free', 'Standing_Dumbbell_Press'],
  'Arnoldpress': ['free', 'Arnold_Dumbbell_Press'],
  'Z-press': null,
  'Maskinpress axlar': ['free', 'Machine_Shoulder_Military_Press'],
  'Landminepress': ['repdb', 'landmine-press'],
  'Kabel-sidolyft': ['free', 'Standing_Low-Pulley_Deltoid_Raise'],
  'Sidolyft hantlar': ['free', 'Side_Lateral_Raise'],
  'Sidolyft': ['free', 'Side_Lateral_Raise'],
  'Sidolyft maskin': null,
  'Kabel upprätt rodd': ['free', 'Upright_Cable_Row'],
  'Omvänd pec deck': ['free', 'Reverse_Machine_Flyes'],
  'Bakre axel kabel': ['free', 'Cable_Rear_Delt_Fly'],
  'Omvända hantelflyes': ['free', 'Reverse_Flyes'],
  'Face pull': ['free', 'Face_Pull'],

  'EZ-curl': ['free', 'EZ-Bar_Curl'],
  'Skivstångscurl': ['free', 'Barbell_Curl'],
  'Preachercurl': ['free', 'Machine_Preacher_Curls'],
  'Lutande hantelcurl': ['free', 'Incline_Dumbbell_Curl'],
  'Hammercurl': ['free', 'Hammer_Curls'],
  'Kabelcurl': ['free', 'Standing_Biceps_Cable_Curl'],
  'Kabelcurl bakom kroppen': null,
  'Rep-curl': ['free', 'Cable_Hammer_Curls_-_Rope_Attachment'],
  'Koncentrationscurl': ['free', 'Concentration_Curls'],
  'Bayesian curl': null,
  'Omvänd curl': ['free', 'Reverse_Barbell_Curl'],

  'Smal bänkpress': ['free', 'Close-Grip_Barbell_Bench_Press'],
  'JM-press': ['free', 'JM_Press'],
  'Triceps pushdown': ['free', 'Triceps_Pushdown'],
  'Pushdown': ['free', 'Triceps_Pushdown'],
  'Triceps rep-pushdown': ['free', 'Triceps_Pushdown_-_Rope_Attachment'],
  'Overhead triceps extension': ['free', 'Cable_Rope_Overhead_Triceps_Extension'],
  'Overhead extension': ['free', 'Cable_Rope_Overhead_Triceps_Extension'],
  'Enarms overhead kabel': ['free', 'Standing_Low-Pulley_One-Arm_Triceps_Extension'],
  'Enarms pushdown': ['free', 'Cable_One_Arm_Tricep_Extension'],
  'Liggande tricepspress': ['free', 'Lying_Triceps_Press'],
  'Liggande hantel-extension': ['free', 'Lying_Dumbbell_Tricep_Extension'],
  'Overhead triceps hantel': ['free', 'Standing_Dumbbell_Triceps_Extension'],
  'Triceps kickback': ['free', 'Tricep_Dumbbell_Kickback'],
  'Maskindips': ['free', 'Dip_Machine'],

  'Handledscurl': ['free', 'Palms-Up_Barbell_Wrist_Curl_Over_A_Bench'],
  'Handledscurl hantlar': ['free', 'Palms-Up_Dumbbell_Wrist_Curl_Over_A_Bench'],
  'Omvänd handledscurl': ['free', 'Palms-Down_Wrist_Curl_Over_A_Bench'],
  'Handledsextension kabel': null,
  'Wrist roller': ['free', 'Wrist_Roller'],
  'Pinch grip hold': ['free', 'Plate_Pinch'],

  'Knäböj': ['free', 'Barbell_Full_Squat'],
  'Frontböj': ['free', 'Front_Barbell_Squat'],
  'Hack squat': ['free', 'Hack_Squat'],
  'Benpress': ['free', 'Leg_Press'],
  'Benpress smal fot': ['free', 'Narrow_Stance_Leg_Press'],
  'Bulgarian split squat': ['free', 'Split_Squat_with_Dumbbells'],
  'Utfall bakåt': ['free', 'Dumbbell_Rear_Lunge'],
  'Step-up': ['free', 'Dumbbell_Step_Ups'],
  'Goblet squat': null,
  'Hälförhöjd goblet squat': null,
  'Benspark': ['free', 'Leg_Extensions'],
  'Benspark enbens': ['free', 'Single-Leg_Leg_Extension'],
  'Spanish squat': null,
  'Sissy squat': null,

  'Rumänska marklyft': ['free', 'Romanian_Deadlift'],
  'Rumänska marklyft hantlar': ['repdb', 'dumbbell-romanian-deadlift'],
  'Enbens RDL': null,
  'Good mornings': ['free', 'Stiff_Leg_Barbell_Good_Morning'],
  'Sittande lårcurl': ['free', 'Seated_Leg_Curl'],
  'Liggande lårcurl': ['free', 'Lying_Leg_Curls'],
  'Lårcurl': ['free', 'Lying_Leg_Curls'],
  'Nordic hamstring curl': ['free', 'Floor_Glute-Ham_Raise'],
  'Glute-ham raise': ['free', 'Natural_Glute_Ham_Raise'],

  'Hip thrust': ['free', 'Barbell_Hip_Thrust'],
  'Hip thrust hantel': null,
  'Glute bridge': ['free', 'Butt_Lift_Bridge'],
  'Glute kickback kabel': ['free', 'One-Legged_Cable_Kickback'],
  'Frog pumps': null,
  'Abduktormaskin': ['free', 'Thigh_Abductor'],
  'Sidogång band': ['free', 'Monster_Walk'],
  'Adduktormaskin': ['free', 'Thigh_Adductor'],

  'Stående vadpress': ['free', 'Standing_Calf_Raises'],
  'Stående vadpress hantlar': ['free', 'Standing_Dumbbell_Calf_Raise'],
  'Sittande vadpress': ['free', 'Seated_Calf_Raise'],
  'Donkey calf raise': null,
  'Vadpress i benpress': ['free', 'Calf_Press_On_The_Leg_Press_Machine'],
  'Enbens vadpress': null,
  'Vadpress': ['free', 'Standing_Calf_Raises'],

  'Cable crunch': ['free', 'Cable_Crunch'],
  'Hängande benlyft': ['free', 'Hanging_Leg_Raise'],
  'Ab wheel': ['free', 'Ab_Roller'],
  'Planka': ['free', 'Plank'],
  'Dead bug': ['free', 'Dead_Bug'],
  'Omvänd crunch': ['free', 'Reverse_Crunch'],
  'Crunch': ['free', 'Crunches'],
  'Pallof press': ['free', 'Pallof_Press'],
  'Copenhagen plank': null,
  'Sidoplanka': ['free', 'Side_Bridge']
});
